### ISSUE TITLE
Create Pangea Website

### ISSUE THREAD

**Issue by shayansal** [Tonomy-Foundation/Tonomy-ID-BD#238] opened 2023-12-13 08:45 UTC
- Use Shahriar webflow template research
- Find template
- Translate Pangea document into webflow website content
- Add additional context and structure for the Site, also refer to the story document
- Define what goes onto each page, sections

pangea strategy: https://docs.google.com/document/d/1qCHvBiHFZJDE1N_R_dO59f_Rznbg7lRkPooAb8hWcyE/edit
tonomy white paper: https://docs.google.com/document/d/1CBObS9XX6Q68Fy54QjK9oZWTdNfqNFS-cTHxCvY3kkQ/edit
story: https://docs.google.com/document/d/1wuLKghFEDhNWo9C-eVLeqoZA--z67y9m7lbrJfP-8NE/edit#heading=h.mcxh3kxzckro

**Comment by theblockstalk** [comment] 2024-02-09 08:34
duplicate of https://github.com/Tonomy-Foundation/Tonomy-ID-BD/issues/243

**Closed as completed** 2024-02-09 08:33 UTC
